torchrun --standalone --nproc_per_node=1 train_gpt2_lightrnn_cocont_mtp.py \
  --input_bin "data/fineweb10B/fineweb_train_*.bin" \
  --input_val_bin "data/fineweb10B/fineweb_val_*.bin" \
  --output_dir pylog124M_lightrnn \
  --model d12 \
  --batch_size 16 \
  --grad_accumulation_steps 8 \
  --sequence_length 1024 \
  --val_loss_every 128 \
  --val_batch_size 16 \
  --num_iterations 5500 \
  --weight_decay 0.1 \
  --learning_rate 0.0045 \
  --warmup_iters 256 \
  --warmdown_iters 3000 \
  --target_val_loss 3.3821 \
  --tie_embedding light \
  --table_size 256 \
  --use_cocont \
  --cocont_alpha 0.1 \
  --ngram_path "data/fineweb10B/bigram_topk16.pt" \
  --ngram_k 16 \
  --precision bf16 \
  --log_wandb
