torchrun --standalone --nproc_per_node=1 train_gpt2_lightrnn_afno.py \
  --input_bin "data/fineweb10B/fineweb_train_*.bin" \
  --input_val_bin "data/fineweb10B/fineweb_val_*.bin" \
  --output_dir pylog124M_lightrnn \
  --model d12 \
  --batch_size 32 \
  --grad_accumulation_steps 16 \
  --sequence_length 2048 \
  --val_loss_every 64 \
  --val_batch_size 32 \
  --num_iterations 5000 \
  --weight_decay 0.1 \
  --learning_rate 0.0018 \
  --warmup_iters 256 \
  --warmdown_iters 1024 \
  --target_val_loss 3.3821 \
  --tie_embedding light \
  --mixer afno \
  --adaptive_softmax \
  --asoft_cutoffs "2000,10000" \
  --asoft_div_value 4.0 \
  --log_wandb
